name: Build and Push
on: ["push", "pull_request"]

jobs:
  build_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.4.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build the page
        run: bundle exec jekyll build

      - name: Check for broken links
        run: "bundle exec htmlproofer --assume-extension --allow-hash-href ./_site || true"

      - name: Push to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/source' && github.event_name == 'push'
        with:
          folder: _site
          branch: master
